### ISSUE TITLE
NcEmojiPicker: Search label is cut

### ISSUE THREAD

**Issue by ShGKme** [nextcloud-libraries/nextcloud-vue#4473]
Seems to be a regression of: https://github.com/nextcloud-libraries/nextcloud-vue/pull/4394

![image](https://github.com/nextcloud-libraries/nextcloud-vue/assets/25978914/0a31c510-1df5-4ec4-a6cf-94ee5f81783d)

**Comment by ShGKme** [comment]
Caused by
```css
.search .input-field__label {
    padding: 5px 4px;
}
```
