### ISSUE TITLE
[NcAppNavigation] Default slot to small for content

### ISSUE THREAD

**Issue by dartcafe** [nextcloud-libraries/nextcloud-vue#6079]
.app-navigation__body does not grow to full content and add uncessary scrolling.

See https://github.com/nextcloud/polls/issues/3704

![grafik](https://github.com/user-attachments/assets/cd5c3c8f-93c9-47c9-a441-c5344e13fe20)

```css
.app-navigation__body {
	flex: 1 0 auto;
}
```
