### ISSUE TITLE
[next] `NcDateTimePicker` popover too small

### ISSUE THREAD

**Issue by raimund-schluessler** [nextcloud-libraries/nextcloud-vue#6494]
The popover of `NcDateTimePicker` is to small on the `next` branch, the right side buttons overflow the parent container.

![Image](https://github.com/user-attachments/assets/fc520044-2e8d-4d75-9b9d-4aa00c6f1da2)

This happens, because of this rule.
```css
.mx-date-time {
  position: relative;
  width: 248px;
  height: 270px
}
```

![Image](https://github.com/user-attachments/assets/b7d5e59c-6933-48d4-9c22-4a2b913b1067)

Adding
```css
.mx-date-time {
  width: unset;
}
```
would fix it, but I don't know whether this would have side-effects.
